import Head from 'next/head'
import { useQuery } from 'urql'
import { PRODUCTS_QUERY } from '../libs/query'
import Product from '@/components/Product'
import { ProductInterface } from '@/types/types'

export default function Home() {

  // Fetch Data
  const [result] = useQuery({
    query: PRODUCTS_QUERY
  })
  const { data, fetching, error } = result;
  if (fetching) return <p>Loading...</p>;
  if (error) return <p>Oh no... {error.message}</p>;
  const products: Array<ProductInterface> = data.products.data

  console.log(products);






  return (
    <>
      <Head>
        <title>Clothing Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {products.map((product: ProductInterface) => (
        <Product key={product.id} image={product.attributes.image.data.attributes.formats.small.url} price={product.attributes.price} title={product.attributes.title} />
      ))}

    </>
  )
}
